-- Oponentes NPC (user_id=0) na tabela character. Gerado; nao editar a mao.
USE `herozero`;
DELETE FROM `character` WHERE user_id = 0;

INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25215,0,'AlineeSantos','f',4,426,14,19,22,17,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (24764,0,'dheje','f',5,180,12,11,10,27,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25232,0,'InspiredSkywalker','f',2,243,12,11,15,10,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25227,0,'AJUDANTEDEMETEU1','m',2,295,10,14,10,14,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25146,0,'ThrillingHero','m',2,209,10,16,11,14,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25106,0,'Kae7ano','m',4,359,38,14,27,67,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25179,0,'padrastodogallea777','m',10,359,35,25,43,47,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25285,0,'erouldl','m',4,320,23,14,42,24,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25242,0,'MANOMIDAS','m',3,295,17,26,34,14,100,100,10,10,'','[]');
INSERT INTO `character` (id,user_id,name,gender,level,honor,stat_base_stamina,stat_base_strength,stat_base_critical_rating,stat_base_dodge_rating,quest_energy,max_quest_energy,duel_stamina,max_duel_stamina,tutorial_flags,new_user_voucher_ids) VALUES (25228,0,'khhh','m',5,171,20,14,15,22,100,100,10,10,'','[]');
